version : "3"
services :
  postgres:
    image: postgres:latest
    container_name: pg_container
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/restore:/restore
    environment:
      - POSTGRES_PASSWORD=hello*
      - POSTGRES_USER=hello_user
      - POSTGRES_DB=hello_db

